# Generated by Django 5.2.4 on 2025-07-13 03:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_startup_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='startup',
            new_name='startupIdea',
        ),
    ]
