# Generated by Django 5.2.4 on 2025-07-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_startupevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='startupEvaluation',
        ),
    ]
