# Generated by Django 5.2.4 on 2025-07-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_delete_startupevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupidea',
            old_name='startup_name',
            new_name='startup_name',
        ),
    ]
