# Generated by Django 5.2.4 on 2025-07-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_rename_startupname_startupidea_startupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_text', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.startupidea')),
            ],
        ),
    ]
