# Generated by Django 5.2.4 on 2025-07-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_startupevaluation'),
    ]

    operations = [
    ]
