# Generated by Django 5.2.4 on 2025-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20250716_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='tags',
            field=models.TextField(default='General'),
        ),
    ]
