# Generated by Django 5.2.4 on 2025-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_startupidea_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupevaluation',
            name='market_trends',
            field=models.TextField(default=''),
        ),
    ]
