# Generated by Django 5.2.4 on 2025-07-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_startupevaluation_swot_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupevaluation',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
