# Generated by Django 5.2.4 on 2025-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_startupevaluation_areas_for_improvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupevaluation',
            name='next_steps',
            field=models.TextField(default=''),
        ),
    ]
